remote_theme: sproogen/resume-theme
name: "Ruoxi Sun"
title: "IMIS | HR-AI Intern"
email: "2024363037@mails.szu.edu.cn"
github_username: x4rbzjvmcx-oss
about_profile_image: images/profile.jpg
about_content: |
  Student at Shenzhen University.
  Skills: <mark>C/C++</mark>, <mark>Python</mark>
content:
  - title: "Projects"
    layout: list
    content:
      - layout: left
        title: "HR Analytics"
        description: |
          Analysis of employee attrition data.
  - title: "Education"
    layout: list
    content:
      - layout: left
        title: "Shenzhen University"
        sub_title: "IMIS"
        description: |
          BSc in Information Management.
plugins:
  - jekyll-seo-tag
